# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import QMainWindow, QApplication
from MainWinUI import Ui_MainWindow


class Ui_login(object):
    login_success_signal = pyqtSignal()

    def __init__(self):
        self.Button_login = None
        self.registerWidget = None
        self.Button_back = None
        self.label_password = None
        self.label_name = None
        self.Button_toregister = None
        self.login_name = None
        self.login_password = None
        self.gridLayout = None
        self.loginWidget = None
        self.verticalLayout_2 = None
        self.scrollArea_2 = None
        self.scrollArea = None
        self.AppTitle = None
        self.verticalLayout = None
        self.centralwidget = None
        self.register_name = None

    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(450, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login.sizePolicy().hasHeightForWidth())
        login.setSizePolicy(sizePolicy)
        login.setMinimumSize(QtCore.QSize(450, 300))
        login.setMaximumSize(QtCore.QSize(450, 300))
        self.centralwidget = QtWidgets.QWidget(parent=login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AppTitle = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AppTitle.sizePolicy().hasHeightForWidth())
        self.AppTitle.setSizePolicy(sizePolicy)
        self.AppTitle.setMinimumSize(QtCore.QSize(230, 50))
        self.AppTitle.setMaximumSize(QtCore.QSize(230, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.AppTitle.setFont(font)
        self.AppTitle.setObjectName("AppTitle")
        self.verticalLayout.addWidget(self.AppTitle, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea_2 = QtWidgets.QWidget()
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 413, 424))
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollArea_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginWidget = QtWidgets.QWidget(parent=self.scrollArea_2)
        self.loginWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginWidget.sizePolicy().hasHeightForWidth())
        self.loginWidget.setSizePolicy(sizePolicy)
        self.loginWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.loginWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.loginWidget.setObjectName("loginWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.loginWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.login_password = QtWidgets.QLineEdit(parent=self.loginWidget)
        self.login_password.setObjectName("login_password")
        self.gridLayout.addWidget(self.login_password, 1, 1, 1, 1)
        self.login_name = QtWidgets.QLineEdit(parent=self.loginWidget)
        self.login_name.setObjectName("login_name")
        self.gridLayout.addWidget(self.login_name, 0, 1, 1, 1)
        self.Button_toregister = QtWidgets.QPushButton(parent=self.loginWidget)
        self.Button_toregister.setObjectName("Button_toregister")
        self.gridLayout.addWidget(self.Button_toregister, 2, 0, 1, 1)
        self.label_name = QtWidgets.QLabel(parent=self.loginWidget)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 0, 1, 1)
        self.label_password = QtWidgets.QLabel(parent=self.loginWidget)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 1, 0, 1, 1)
        self.Button_login = QtWidgets.QPushButton(parent=self.loginWidget)
        self.Button_login.setObjectName("Button_login")
        self.gridLayout.addWidget(self.Button_login, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.loginWidget)
        self.registerWidget = QtWidgets.QWidget(parent=self.scrollArea_2)
        self.registerWidget.setEnabled(True)
        self.registerWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.registerWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.registerWidget.setObjectName("registerWidget")
        self.registerWidget.hide()
        self.gridLayout_2 = QtWidgets.QGridLayout(self.registerWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_register_name = QtWidgets.QLabel(parent=self.registerWidget)
        self.label_register_name.setObjectName("label_register_name")
        self.gridLayout_2.addWidget(self.label_register_name, 0, 0, 1, 1)
        self.register_name = QtWidgets.QLineEdit(parent=self.registerWidget)
        self.register_name.setObjectName("register_name")
        self.gridLayout_2.addWidget(self.register_name, 0, 1, 1, 1)
        self.label_register_password = QtWidgets.QLabel(parent=self.registerWidget)
        self.label_register_password.setObjectName("label_register_password")
        self.gridLayout_2.addWidget(self.label_register_password, 1, 0, 1, 1)
        self.label_register_confirm = QtWidgets.QLabel(parent=self.registerWidget)
        self.label_register_confirm.setObjectName("label_register_confirm")
        self.gridLayout_2.addWidget(self.label_register_confirm, 2, 0, 1, 1)
        self.register_password = QtWidgets.QLineEdit(parent=self.registerWidget)
        self.register_password.setObjectName("register_password")
        self.gridLayout_2.addWidget(self.register_password, 1, 1, 1, 1)
        self.register_confirm = QtWidgets.QLineEdit(parent=self.registerWidget)
        self.register_confirm.setObjectName("register_confirm")
        self.gridLayout_2.addWidget(self.register_confirm, 2, 1, 1, 1)
        self.Button_register = QtWidgets.QPushButton(parent=self.registerWidget)
        self.Button_register.setObjectName("Button_register")
        self.gridLayout_2.addWidget(self.Button_register, 3, 1, 1, 1)
        self.Button_back = QtWidgets.QPushButton(parent=self.registerWidget)
        self.Button_back.setObjectName("Button_back")
        self.gridLayout_2.addWidget(self.Button_back, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.registerWidget)
        self.scrollArea.setWidget(self.scrollArea_2)
        self.verticalLayout.addWidget(self.scrollArea)
        login.setCentralWidget(self.centralwidget)

        self.retranslateUi(login)
        self.Button_toregister.clicked.connect(self.Button_toregister_click)  # type: ignore
        self.Button_back.clicked.connect(self.Button_back_click)  # type: ignore
        self.Button_login.clicked.connect(self.Button_login_clicked)
        self.Button_register.clicked.connect(self.Button_register_clicked)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Login"))
        self.AppTitle.setText(_translate("login", "智能图像生成器"))
        self.Button_toregister.setText(_translate("login", "注册"))
        self.label_name.setText(_translate("login", "用户名："))
        self.label_password.setText(_translate("login", "密码："))
        self.Button_login.setText(_translate("login", "登录"))
        self.label_register_name.setText(_translate("login", "用户名："))
        self.label_register_password.setText(_translate("login", "密码："))
        self.label_register_confirm.setText(_translate("login", "确认密码："))
        self.Button_register.setText(_translate("login", "注册"))
        self.Button_back.setText(_translate("login", "返回登陆"))

    def Button_back_click(self):
        self.loginWidget.show()
        self.registerWidget.hide()
        self.register_name.clear()
        self.register_password.clear()
        self.register_confirm.clear()

    def Button_toregister_click(self):
        self.loginWidget.hide()
        self.registerWidget.show()
        self.login_name.clear()
        self.login_password.clear()

    def Button_login_clicked(self):
        username = self.login_name.text()
        password = self.login_password.text()
        print(username + password)
        MainGUI()



    def Button_register_clicked(self):
        username = self.register_name.text()
        password = self.register_password.text()
        confirm = self.register_confirm.text()
        print(username + password + confirm)


class MainGUI(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    loginWindow = MainGUI()
    loginWindow.show()
    sys.exit(app.exec())
